### ISSUE TITLE
The haproxy_pod.yaml.j2 template produces a broken yaml

### ISSUE THREAD

**Issue by rascasoft** [mmul-it/kubelab#3]
If `k8s_ingress_nginx_haproxy_conf` is set to true, then the `haproxy.yaml` produced is broken, as follows:

```yaml
  containers:
  - image: haproxy:2.8
    name: haproxy
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: localhost
        path: /healthz
        port: 8443
        scheme: HTTPS
        securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
      runAsUser: 0
        volumeMounts:
    - mountPath: /usr/local/etc/haproxy/haproxy.cfg
      name: haproxyconf
      readOnly: true
```

This must be fixed.
